swagger: "2.0"
info:
  description: Alpha version of the True NTH portal RESTful API, to be used by True NTH intervention applications. Can be found at https://raw.githubusercontent.com/uwcirg/true_nth_usa_services/master/true-nth-portal.yaml . This API attempts to conform with the HL7 FHIR specification as much as is reasonable.
  version: "1.0.0"
  title: True NTH Portal
  termsOfService: http://cirg.washington.edu
  contact:
    name: Clinical Informatics Reserach Group
    email: mcjustin@uw.edu
    url: http://cirg.washington.edu
  license:
    name: MIT
    url: http://opensource.org/licenses/MIT
host: usa.truenth.org
basePath: /portal/api
schemes:
  - http
paths:
  /demographics:
    get:
      summary: Get patient demographics
      description: "Returns a patient's demographics fields (eg first name, last name, DOB, email, cell phone)."
      operationId: getPatientById
      produces:
        - application/json
        - application/xml
      parameters:
        - name: patientId
          in: query
          description: True NTH patient ID. If patientId isn't passed, the authenticated user's ID is used.
          required: false
          type: integer
          format: int64
      responses:
        "404":
          description: Patient not found
        "200":
          description: successful operation
          schema:
            $ref: "#/definitions/Patient"
        "400":
          description: Invalid ID supplied
      security:
        - api_key: []
        - patientportal_auth:
          - write_patients
          - read_patients
  /clinical:
    get:
      summary: Get patient clinical data
      description: "Returns a patient's clinical data (eg TNM, Gleason score)."
      operationId: getClinicalByPatientId
      produces:
        - application/json
        - application/xml
      parameters:
        - name: patientId
          in: query
          description: True NTH patient ID. If patientId isn't passed, the authenticated user's ID is used.
          required: false
          type: integer
          format: int64
      responses:
        "404":
          description: Patient not found
        "200":
          description: successful operation
          schema:
            $ref: "#/definitions/Clinical"
        "400":
          description: Invalid ID supplied
      security:
        - api_key: []
        - patientportal_auth:
          - write_patients
          - read_patients
  /questionnaire:
    get:
      summary: Get patient's responses to questionnaires 
      description: "Returns a patient's responses to questionnaires/assessments presented by the portal's assessment engine."
      operationId: getQuestionnaireByPatientId
      produces:
        - application/json
        - application/xml
      parameters:
        - name: patientId
          in: query
          description: True NTH patient ID. If patientId isn't passed, the authenticated user's ID is used.
          required: false
          type: integer
          format: int64
        - name: questionnaireId
          in: query
          description: True NTH patient ID
          required: true
          type: integer
          format: int64
      responses:
        "404":
          description: Patient not found
        "200":
          description: successful operation
          schema:
            $ref: "#/definitions/Questionnaire"
        "400":
          description: Invalid ID supplied
      security:
        - api_key: []
        - patientportal_auth:
          - write_patients
          - read_patients
  /portal-wrapper-html:
    get:
      summary: Get html for the portal site UI wrapper (top-level nav elements, etc)
      description: ""
      operationId: portal-wrapper-html
      produces:
        - text/html
      responses:
        "200":
          description: successful operation
        "404":
          description: Portal wrapper html not found
        "500":
          description: Portal internal server error
securityDefinitions:
  api_key:
    type: apiKey
    name: api_key
    in: header
  patientportal_auth:
    type: oauth2
    authorizationUrl: https://usa.truenth.org/api/oauth/dialog
    flow: implicit
    scopes:
      write_patients: modify patients in your account
      read_patients: read your patients
definitions:
  Patient:
    externalDocs:
      url: http://www.hl7.org/fhir/patient.html
    required:
      - id
    properties:
      id:
        type: integer
        format: int64
      name:
        externalDocs:
          url: http://www.hl7.org/fhir/patient-definitions.html#Patient.name
        $ref: "#/definitions/HumanName"        
      birthDate:
        type: string
        format: date-time
        externalDocs:
          url: http://www.hl7.org/fhir/patient-definitions.html#Patient.birthDate
      communication:
        type: string
        description: preferred language
        example: es-MX, en-US
        externalDocs: 
          url: http://www.hl7.org/fhir/patient-definitions.html#Patient.communication
      telecom:
        type: array
        externalDocs: 
          url: http://www.hl7.org/fhir/patient-definitions.html#Patient.telecom
        items:
          type: object
          properties:
            system: 
              type: string
              example: email | phone
            value:
              type: string
              example: helloworld@movember.com; (123) 456-7890
      status:
        type: string
        description: patient status in the portal

  HumanName:
    externalDocs:
      url: http://www.hl7.org/fhir/datatypes.html#HumanName
    properties:
      family:
        type: string
      given:
        type: string

  Clinical:
    properties:
      TNM-Condition-stage:
        description: TNM staging for prostate cancer. This is a bit of a mashup - not doing full FHIR Condition, as that seems like overkill here. Do we want this to be machine interpretable? If so, we might want to formalize the "summary". Note that using the HL7/FHIR "summary" property here is a little confusing, since swagger has its own use of the summary element (which is more about documenting the service). 
        type: object
        externalDocs:
          url: https://www.hl7.org/fhir/condition.html ; https://www.hl7.org/fhir/condition-definitions.html#Condition.stage
        properties:
          summary: 
            $ref: "#/definitions/CodeableConcept"
            example: "T1 N0 M0"
      Gleason-score:
        description: Includes a sum (2-10) of the primary and secondary pattern scores (both of which are 1-5). SNOMED-CT coded. http://phinvads.cdc.gov/vads/ViewCodeSystemConcept.action?oid=2.16.840.1.113883.6.96&code=372278000. 
        example: "5 ( 2 + 3)"

  CodeableConcept:
    externalDocs:
      url: https://www.hl7.org/fhir/datatypes.html#CodeableConcept
    properties:
      coding:
        type: string
      text:
        type: string
        example: "T1 N0 M0"

  Questionnaire:
    description: A patient's responses to a questionnaire (a set of instruments, some standardized, some not), and metadata about the presentation and context of the assessment session (date, etc). 
    externalDocs:
      url: http://www.hl7.org/implement/standards/fhir/questionnaire.html
    properties:
      status:
        externalDocs:
          url: http://www.hl7.org/implement/standards/fhir/questionnaire-status.html
        description: "'in progress' or 'completed'"
        type: string
      subject:
        description: Only need return Patient.id here.
        $ref: "#/definitions/Patient"        
        externalDocs:
          url: http://www.hl7.org/implement/standards/fhir/questionnaire-definitions.html#Questionnaire.subject
      name:
        description: The name of the instrument presented (eg PHQ-9, EPIC-26). Instrument name set TBD. FHIR specifies coded concepts for this but I think that's overly complex for our purposes, for now at least (http://www.hl7.org/implement/standards/fhir/valueset-questionnaire-name.html)
        type: string
      encounter:
        description: The encounter during which the patient completed the assessment. This is currently constrained to a True NTH portal or intervention encounter. 
        type: object
        externalDocs:
          url: http://www.hl7.org/implement/standards/fhir/encounter.html
        properties:
          period:
            description: The datetime of the patients last interaction with the questionnaire.
            type: string
            format: date-time
            externalDocs:
              url: http://www.hl7.org/implement/standards/fhir/search.html#date
      group:
        description: Grouping of individual instruments presented during this assessment session, standardized or otherwise.
        type: object
        externalDocs:
          url: http://www.hl7.org/implement/standards/fhir/questionnaire-definitions.html#Questionnaire.group
        properties:
          question: 
            description: THIS OBVIOUSLY NEEDS TO BE REFACTORED FOR n QUESTIONS / GROUP...