swagger: "2.0"
info:
  description: Alpha version of the True NTH portal RESTful API, to be used by True NTH intervention applications. Can be found at https://raw.githubusercontent.com/uwcirg/true_nth_usa_services/master/true-nth-portal.yaml 
  version: "1.0.0"
  title: True NTH Portal
  termsOfService: http://cirg.washington.edu
  contact:
    name: Clinical Informatics Reserach Group
    email: mcjustin@uw.edu
    url: http://cirg.washington.edu
  license:
    name: MIT
    url: http://opensource.org/licenses/MIT
host: usa.truenth.org
basePath: /portal/api
schemes:
  - http
paths:
  /demographics/{patientId}:
    get:
      tags:
        - patient
      summary: Get patient demographics
      description: Returns a patient's demographics fields (eg first name, last name, DOB, email, cell phone). If patientId isn't passed, the authenticated user's demographics data are returned
      operationId: getPatientById
      produces:
        - application/json
        - application/xml
      parameters:
        - in: path
          name: patientId
          description: ID of patient that needs to be fetched
          required: false
          type: integer
          format: int64
      responses:
        "404":
          description: Patient not found
        "200":
          description: successful operation
          schema:
            $ref: "#/definitions/Patient"
        "400":
          description: Invalid ID supplied
      security:
        - api_key: []
        - patientportal_auth:
          - write_patients
          - read_patients
  /clinical/{patientId}:
    get:
      tags:
        - patient
      summary: Get patient clinical data
      description: Returns a patient's clinical data (eg TNM, Gleason score). If patientId isn't passed, the authenticated user's clinical data are returned
      operationId: getPatientById
      produces:
        - application/json
        - application/xml
      parameters:
        - in: path
          name: patientId
          description: ID of patient that needs to be fetched
          required: false
          type: integer
          format: int64
      responses:
        "404":
          description: Patient not found
        "200":
          description: successful operation
          schema:
            $ref: "#/definitions/Clinical"
        "400":
          description: Invalid ID supplied
      security:
        - api_key: []
        - patientportal_auth:
          - write_patients
          - read_patients
securityDefinitions:
  api_key:
    type: apiKey
    name: api_key
    in: header
  patientportal_auth:
    type: oauth2
    authorizationUrl: https://usa.truenth.org/api/oauth/dialog
    flow: implicit
    scopes:
      write_patients: modify patients in your account
      read_patients: read your patients
definitions:
  User:
    properties:
      id:
        type: integer
        format: int64
      username:
        type: string
      firstName:
        type: string
      lastName:
        type: string
      email:
        type: string
      password:
        type: string
      phone:
        type: string
      userStatus:
        type: integer
        format: int32
        description: User Status
  Category:
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
  Patient:
    externalDocs:
      url: http://www.hl7.org/fhir/patient.html
    required:
      - id
    properties:
      id:
        type: integer
        format: int64
      name:
        externalDocs:
          url: http://www.hl7.org/fhir/patient-definitions.html#Patient.name
        $ref: "#/definitions/HumanName"        
      birthDate:
        type: string
        format: date-time
        externalDocs:
          url: http://www.hl7.org/fhir/patient-definitions.html#Patient.birthDate
      communication:
        type: string
        description: preferred language
        example: es-MX, en-US
        externalDocs: 
          url: http://www.hl7.org/fhir/patient-definitions.html#Patient.communication
      telecom:
        type: array
        externalDocs: 
          url: http://www.hl7.org/fhir/patient-definitions.html#Patient.telecom
        items:
          type: object
          properties:
            system: 
              type: string
              example: email | phone
            value:
              type: string
              example: helloworld@movember.com; (123) 456-7890
      category:
        $ref: "#/definitions/Category"
      photoUrls:
        type: array
        items:
          type: string
      tags:
        type: array
        items:
          $ref: "#/definitions/Tag"
      status:
        type: string
        description: patient status in the portal
  Tag:
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
  HumanName:
    externalDocs:
      url: http://www.hl7.org/fhir/datatypes.html#HumanName
    properties:
      family:
        type: string
      given:
        type: string

  Clinical:
    properties:
      TNM-Condition-stage:
        description: TNM staging for prostate cancer. This is a bit of a mashup - not doing full FHIR Condition, as that seems like overkill here. Do we want this to be machine interpretable? If so, we might want to formalize the "summary". 
        type: object
        externalDocs:
          url: https://www.hl7.org/fhir/condition.html ; https://www.hl7.org/fhir/condition-definitions.html#Condition.stage
        properties:
          summary: 
            $ref: "#/definitions/CodeableConcept"
            example: "T1 N0 M0"
        
  CodeableConcept:
    externalDocs:
      url: https://www.hl7.org/fhir/datatypes.html#CodeableConcept
    type: object
      properties:
        coding:
          type: string
        text:
          type: string
          example: "T1 N0 M0"
          
  Order:
    properties:
      id:
        type: integer
        format: int64
      patientId:
        type: integer
        format: int64
      quantity:
        type: integer
        format: int32
      shipDate:
        type: string
        format: date-time
      status:
        type: string
        description: Order Status
      complete:
        type: boolean
